name = "web"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Environment Variables
[env.preview.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://wmghucwmjnbqpsujncee.supabase.co"
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAABDJBdKrAc35rNYp"
NEXT_PUBLIC_POSTHOG_KEY = "phc_4ozFzjv9pS6t7nEKHvYzwTt7uLBNhRvx65jlkpoirtV"
NEXT_PUBLIC_TINKER_MONTHLY_PRICE_ID = "price_1RLUtTGSS5XC9znc6IMUFKXn"
NEXT_PUBLIC_TINKER_YEARLY_PRICE_ID = "price_1RLUtmGSS5XC9zncygmaPmwB"
NEXT_PUBLIC_FLOW_MONTHLY_PRICE_ID = "price_1RLUvvGSS5XC9zncibcYCzUV"
NEXT_PUBLIC_FLOW_YEARLY_PRICE_ID = "price_1RLUwTGSS5XC9zncUwHsUash"
NEXT_PUBLIC_OPTIMIZE_MONTHLY_PRICE_ID = "price_1RLUuoGSS5XC9zncOzaG7oDR"
NEXT_PUBLIC_OPTIMIZE_YEARLY_PRICE_ID = "price_1RLUvCGSS5XC9zncLDGd4G0S"

[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://krleqnhlvnyqtkqoyogw.supabase.co"
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAABDJBdKrAc35rNYp"
NEXT_PUBLIC_POSTHOG_KEY = "phc_4ozFzjv9pS6t7nEKHvYzwTt7uLBNhRvx65jlkpoirtV"
NEXT_PUBLIC_TINKER_MONTHLY_PRICE_ID = "price_1RBwaWGSS5XC9znc2b0id4Oa"
NEXT_PUBLIC_TINKER_YEARLY_PRICE_ID = "price_1RBwauGSS5XC9zncnK8ztUHB"
NEXT_PUBLIC_FLOW_MONTHLY_PRICE_ID = "price_1R8pY3GSS5XC9znca9MI7G8W"
NEXT_PUBLIC_FLOW_YEARLY_PRICE_ID = "price_1R8pZQGSS5XC9znctdxrxOxj"
NEXT_PUBLIC_OPTIMIZE_MONTHLY_PRICE_ID = "price_1R8pc0GSS5XC9zncDhljuzTa"
NEXT_PUBLIC_OPTIMIZE_YEARLY_PRICE_ID = "price_1R8pcnGSS5XC9zncfrC8Cn9r"
