name: Deploy Pages Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Pages Production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: npm install --force && npm run pages:build && wrangler pages deploy
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: 'prd'
