name: Deploy Pages Preview

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Pages Preview
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run pages:build
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL_DEV }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL_DEV }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY_DEV }}
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./site/out
          retention-days: 2
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Pages Preview
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: ./site
      - name: Publish
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --project-name=web ./site
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: 'preview'
